### ISSUE TITLE
I would like to fix some typos in README.md in first page

### ISSUE THREAD

**Issue by denmark111** [housekorea/pfc#1]
I really want to contribute to this project, but I see most of the code is in python which I'm still learning :-)  
So as of right now I would like to fix some typos and misspelling in main page's README.md.  
(and hopefully I can contribute by fixing some actual code with python later)
Will that be fine?

**Comment by housekorea** [comment]
Yes, you can. Please!

I'm not a native speaker of English. But I know "English" is the best language to share knowledge and codes. If you can contribute this PFC project, I am very helpful with thanks.

And, please to talk me about any idea or suggestion to developing this project. 

In recent time, I would change the code to develop followings.

1) Integration AWS IoT Architecture based QoS 0 Level. 
2) USB Serial Communication to I2C connection in the between the Raspberry PI, Arduino  ( For maintainable connection)
3)  Change the OpenCV codes. In near future, I would integration "Tensorflow" to measuring and detecting plant.
